language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install -U --only-binary=numpy,scipy numpy scipy mpmath
install:
  - python setup.py install
script:
  nosetests --verbosity=2

notifications:
  email: false
